### ISSUE TITLE
Review 

### ISSUE THREAD

**Issue by tomicmario** [AMT-TEAM01/Rekognition#5]
@NicolasGlassey 

https://github.com/AMT-TEAM01/Rekognition/commit/2484e3e80826b2e48f628f7a1ee12be94c61e957

**Comment by NicolasGlassey** [comment]
@JanisChiffelle  @tomicmario 

Bonsoir Messieurs,

J'ai pu exécuter votre livrable sur AWS.

Bonne documentation !

A demain.
Nicolas Glassey
